services:
  backstage:
    build: .
    restart: unless-stopped
    ports:
      - '42069:42069'
      - '42070:42070'
    volumes:
      - type: bind
        source: ${VAM_ROOT_MOUNT:-/mnt/vam-root}
        target: /vam
      - type: bind
        source: ${VAM_STORAGE_MOUNT:-/mnt/vam-storage}
        target: ${VAM_STORAGE_TARGET:-/??/D:/games/vam}
      - type: volume
        source: backstage-data
        target: /data

volumes:
  backstage-data:
